# seata config
seata:
  enabled: true
  application-id: ${spring.application.name}
  # 是否启用数据源bean的自动代理
  enable-auto-data-source-proxy: true
  tx-service-group: dev_tx_group   # 事务群组（可以每个应用单独取名，也可以使用相同名字，独立起名需要配置nacos）
  registry:
    type: nacos
    nacos:
      server-addr: localhost:8848
      namespace: 79622650-2ad0-4651-945e-82929157836f
      group: SEATA_GROUP
      application: seata-server # 必须和服务器配置一样
      username: nacos
      password: nacos
      cluster: default
  config:
    type: nacos
    nacos:
      namespace: 79622650-2ad0-4651-945e-82929157836f
      server-addr: localhost:8848
      group: SEATA_GROUP
      username: nacos
      password: nacos
      dataId: seata.properties
  service:
    vgroupMapping:
      dev_tx_group: default # 必须和服务器配置一样
#    grouplist:
#      default: 127.0.0.1:8091
#    enable-degrade: false
#    disable-global-transaction: false
  client:
    rm:
      # 是否上报成功状态
      report-success-enable: true
      # 重试次数
      report-retry-count: 5
