is:
  host: localhost
  mysql-port: 3306
  nacos-port: 4408
  redis-port: 6379
  druid-password: 123456

#database
DB_HOST: ${is.host}:${is.mysql-port}
DB_NAME: domain_event
DB_USERNAME: root
DB_PASSWORD: 123456
REDIS_PASSWORD: redis6379