is:
  host: localhost
  mysql-port: 3306
  nacos-port: 4408
  redis-port: 6379
  druid-password: 123456
  mq-host1: localhost
  mq-port1: 10911
  mq-host2: localhost
  mq-port2: 10915
#nacos
nacos:
  #dev
  namespace: 79622650-2ad0-4651-945e-82929157836f
#database
DB_HOST: ${is.host}:${is.mysql-port}
DB_NAME:
DB_USERNAME: root
DB_PASSWORD: 123456
REDIS_PASSWORD: redis6379


MQ_NAME_SERVER: ${is.mq-host1}:${is.mq-port1};${is.mq-host2}:${is.mq-port2}
MQ_GROUP: inventory_management
